#!/bin/sh -e

case "$1" in
    configure)
	echo "xxx xxx configure xxx xxx"

        chown mellow:mellow .bash_aliases
        chown -R mellow:mellow Documents

        ;;

    abort-install|abort-upgrade|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
